SELECT USERNAME
FROM MEMBER
WHERE USERID = ?
AND USERPWD = ?

CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
    P_NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(100),
    STOCK NUMBER NOT NULL
);

COMMIT;

SELECT *
FROM PRODUCT;

-- 1번 조회
SELECT PRODUCT_ID, P_NAME, PRICE, DESCRIPTION, STOCK
FROM PRODUCT;

-- 2번 상품 추가
INSERT INTO PRODUCT (PRODUCT_ID, P_NAME, PRICE, DESCRIPTION, STOCK)
VALUES (?, ?, ?, ?, ?)

-- 3번 상품 수정하기 (상품id로 조회하고 수정)
UPDATE PRODUCT
SET PRODUCT_ID, P_NAME, PRICE, DESCRIPTION, STOCK
WHERE PRODUCT_ID = ?;

-- 4번 상품 삭제하기 (상품id로 조회해서 삭제)
DELETE
FROM PRODUCT
WHERE PRODUCT_ID = ?;

-- 5번 상품 검색하기 (상품 이름으로 키워드 검색)
SELECT PRODUCT_ID, P_NAME, PRICE, DESCRIPTION, STOCK
FROM PRODUCT
WHERE P_NAME = ?;


DROP TABLE PRODUCT_IO;
DROP SEQUENCE SEQ_IO;
CREATE TABLE PRODUCT_IO(
    IO_NUM NUMBER PRIMARY KEY,
    PRODUCT_ID VARCHAR2(20) REFERENCES PRODUCT(PRODUCT_ID),
    IO_DATE DATE DEFAULT SYSDATE NOT NULL,
    AMOUNT NUMBER NOT NULL,
    STATUS VARCHAR2(10) CHECK (STATUS IN('입고', '출고'))
);

CREATE SEQUENCE SEQ_IO
NOCACHE;

--6_1
SELECT * FROM PRODUCT_IO;
--6_2
SELECT * FROM PRODUCT_IO WHERE STATUS = '입고'
--6_3
SELECT * FROM PRODUCT_IO WHERE STATUS = '출고'
--6_4 상품 입고 --> 입고할 상품ID와 입고수량 입력받기, (+)트리거로 한번에 들어가도록 해야 함. (IO에 넣으면 바로 PRODUCT에 들어가도록)
INSERT INTO PRODUCT_IO(IO_NUM, PRODUCT_ID, IO_DATE, AMOUNT, STATUS) VALUES (?, ?, ?, ?, ?)
--6_5 상품 출고 --> 출고할 상품ID와 출고수량 입력받기, (-)
INSERT INTO PRODUCT_IO(IO_NUM, PRODUCT_ID, IO_DATE, AMOUNT, STATUS) VALUES (?, ?, ?, ?, ?)


CREATE OR REPLACE TRIGGER TRG_01
AFTER INSERT ON PRODUCT_IO
FOR EACH ROW
BEGIN
    -- 상품이 입고된 경우 => 재고수량 증가
    IF (:NEW.STATUS = '입고')
        THEN 
            UPDATE PRODUCT
            SET STOCK = STOCK + :NEW.AMOUNT -- 현재 입고된 수량
            WHERE PRODUCT_ID = :NEW.PRODUCT_ID
            AND :NEW.AMOUNT >= 0;
    END IF;
    -- 상품이 출고된 경우 => 재고수량 감소
    IF (:NEW.STATUS = '출고')
        THEN
            UPDATE PRODUCT
            SET STOCK = STOCK - :NEW.AMOUNT -- 현재 출고된 수량
            WHERE PRODUCT_ID = :NEW.PRODUCT_ID
            AND :NEW.AMOUNT >= 0;
    END IF;
END;

INSERT INTO
PRODUCT_IO (IO_NUM, PRODUCT_ID, IO_DATE, AMOUNT, STATUS)
VALUES
(SEQ_IO.NEXTVAL, 'pc_ibm', SYSDATE, 10, '입고');

COMMIT;

SELECT
			 	IO_NUM
			  , PRODUCT_ID
			  , IO_DATE
			  , AMOUNT
			  , STATUS
		  FROM
		  		PRODUCT_IO;


SELECT * FROM PRODUCT;

INSERT INTO
			PRODUCT
				(
				  IO_NUM
				  , PRODUCT_ID
				  , IO_DATE
				  , AMOUNT
				  , STATUS
				)
			 VALUES
			 	(
			 	  SEQ_IO.NEXTVAL
			 	  , 'ㅁㄴㅇㄹ'
			 	  , SYSDATE
			 	  , 111
			 	  , '출고'
			 	);




