SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE USERNAME LIKE '%XXX%';

-- 회원 정보 변경 요청시 실행할 sql문
UPDATE MEMBER
    SET USERPWD = 'XXXX'
        , EMAIL = 'XXXX'
        , PHONE = 'XXXXXXXXX'
        , ADDRESS = 'XXXXXXX'
WHERE USERID = 'XXXX'

-- 회원 탈퇴 시 실행할 sql문
DELETE
FROM MEMBER
WHERE USERID = 'xxxx'
;
DELETE
FROM MEMBER
WHERE USERID = 'USER04';