DROP TABLE BOOK;
DROP TABLE MAGAZINE;
DROP SEQUENCE SEQ_BNO;

CREATE TABLE BOOK(
    BNO VARCHAR2(20) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    AUTHOR VARCHAR2(50) NOT NULL,
    PUBLISHER VARCHAR2(50) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL
);

CREATE TABLE MAGAZINE(
    BNO VARCHAR2(20) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    AUTHOR VARCHAR2(50) NOT NULL,
    PUBLISHER VARCHAR2(50) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(200) NOT NULL,
    YEAR NUMBER NOT NULL,
    MONTH NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_BNO
START WITH 100
NOCACHE;

INSERT INTO MAGAZINE
VALUES(SEQ_BNO, 1);

-- 테이블 자료 만들기

-- 1. 추가하기
INSERT INTO BOOK VALUES (SEQ_BNO.NEXTVAL, '잃어버린 성훈이를 찾아서', '고영훈 박사', '나무 출판사', 8500, '『시연스』, 『르 몽드』 선정 20세기 최고의 책');
INSERT INTO BOOK (BNO, TITLE, AUTHOR, PUBLISHER, PRICE, DESCRIPTION)
VALUES (1, '잃어버린 성훈이를 찾아서', '고영훈 박사', '나무 출판사', 8500, '『시연스』, 『르 몽드』 선정 20세기 최고의 책');

INSERT INTO BOOK VALUES (SEQ_BNO, "1", "1", "1", 8500, "1");

DELETE
FROM BOOK;

-- 2. 조회하기
SELECT *
FROM BOOK;
SELECT *
FROM MAGAZINE;

-- 3. 책 찾기
SELECT * FROM BOOK WHERE BNO = ?
SELECT * FROM BOOK WHERE TITLE LIKE ?
SELECT * FROM MAGAZINE WHEREE YEAR = ?
SELECT * FROM BOOK WHERE PUBLISHER LIKE ?
SELECT * FROM BOOK WHERE PRICE <= ?
;
-- 4. 전체 책 가격 합계 및 평균 조회
SELECT SUM(PRICE) FROM BOOK;
SELECT AVG(PRICE) FROM BOOK;